name: test

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.20.0'

      - name: test
        run: go test ./postgres
  Deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: setup GCP service account
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: kubernetes-351917
          service_account_key: ${{secrets.GCP_SA}}
          export_default_credentials: true

      - name: deploy hello cloud function
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: hello
          runtime: 120
          project_id: kubernetes-351917
          entry_point: Hello

